-- ============================================================================
-- Golden Oven — consolidated database schema (migrations 001–039)
--
-- WHAT THIS IS
--   The complete final state of every migration in supabase/migrations/,
--   flattened into one script. Generated by applying all 36 migration files in
--   order to an empty PostgreSQL 16 database and dumping the result, so it is
--   the schema those migrations actually produce — not a hand-transcription.
--   Redundant history is gone: create_order(), for example, is defined once
--   here instead of the eight times it is rewritten across the migrations.
--
-- WHEN TO USE IT
--   Standing up a NEW Supabase project (e.g. moving to a different account).
--   Paste the whole file into the SQL Editor and Run. It replaces running
--   001–039 by hand.
--
-- WHAT IT CONTAINS
--   Structure only — tables, columns, constraints, indexes, sequences,
--   functions/RPCs, row-level-security policies, grants, and the two storage
--   buckets with their policies.
--
-- WHAT IT DOES *NOT* CONTAIN
--   Rows. No products, orders, packages, delivery tiers, site settings or ops
--   data. That is deliberate: you are importing real data from the old
--   project, and pre-seeded reference rows would collide with it on import.
--   • Migrating an existing project → run this, then import your data
--     (pg_dump --data-only), then copy the storage FILES separately (a SQL
--     dump moves the bucket rows, never the files themselves).
--   • Starting genuinely fresh instead → run this, then supabase/seed.sql and
--     supabase/content.sql for demo catalogue + editable-content rows.
--
-- ASSUMPTIONS
--   A managed Supabase project, which already provides the `auth` and
--   `storage` schemas and the anon / authenticated / service_role roles.
--   Safe to run top-to-bottom exactly once on an empty project.
--
-- VERIFIED
--   Applied to a pristine PostgreSQL 16 database, then compared object-by-object
--   against a database built by replaying all 36 migrations:
--     • 202 table columns  — identical
--     • 19 functions       — identical
--     • 36 indexes         — identical
--     • 59 constraints     — identical (incl. the delivery_slot and
--                            slab_letter_max_chars checks)
--     • policies           — identical, plus the two product-images storage
--                            policies, which live in storage-setup.sql rather
--                            than in a migration and are folded in here.
--   Then smoke-tested on the result: create_order() places an order with a
--   delivery slot, lookup_order() returns it, and anon/authenticated hold the
--   execute grants the storefront needs.
-- ============================================================================

-- uuid_generate_v4() backs most primary keys.
create extension if not exists "uuid-ossp";


-- ============================================================================
-- PUBLIC SCHEMA — tables, functions, RLS policies, grants
-- ============================================================================

-- Functions are created before the tables they read (is_admin() and
-- can_view_ops() both query `profiles`). Deferring body validation lets them be
-- defined in any order; Postgres still resolves them correctly at call time.
set check_function_bodies = false;

\restrict yVAxHxeteQh6057YPAvnZ4WJUoMxENbsRroP9zCCtUT8sXiZ6mIxXXXNYnahFgU



--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--



--
-- Name: inquiry_category; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.inquiry_category AS ENUM (
    'corporate',
    'wedding'
);


--
-- Name: inquiry_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.inquiry_status AS ENUM (
    'new',
    'contacted',
    'quoted',
    'converted',
    'closed'
);


--
-- Name: order_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.order_status AS ENUM (
    'pending',
    'confirmed',
    'baking',
    'ready',
    'out_for_delivery',
    'completed',
    'cancelled'
);


--
-- Name: advance_order_status(uuid, public.order_status); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.advance_order_status(p_id uuid, p_to public.order_status) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
begin
  if auth.uid() is null then
    raise exception 'NOT_AUTHENTICATED';
  end if;
  -- Only the transitions the Kitchen Board exposes (KITCHEN_NEXT in
  -- src/lib/kitchenOrders.ts). Everything else remains admin-only.
  if p_to not in ('baking', 'ready', 'completed') then
    raise exception 'INVALID_KITCHEN_STATUS';
  end if;
  update orders set status = p_to, updated_at = now() where id = p_id;
end;
$$;


--
-- Name: can_view_ops(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.can_view_ops() RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    AS $$
  select coalesce(
    (select role::text from profiles where id = auth.uid()) in ('admin', 'finance'),
    auth.uid() is not null
  );
$$;


--
-- Name: create_order(text, text, text, text, text, date, text, numeric, numeric, numeric, integer, jsonb, text, numeric, boolean, text, text, text, text, text, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.create_order(p_customer_name text, p_phone text, p_email text, p_alt_phone text, p_address text, p_delivery_date date, p_note text, p_subtotal numeric, p_delivery_fee numeric, p_total numeric, p_total_pieces integer, p_items jsonb, p_voucher_code text DEFAULT NULL::text, p_voucher_discount numeric DEFAULT 0, p_is_gift boolean DEFAULT false, p_recipient_name text DEFAULT NULL::text, p_recipient_phone text DEFAULT NULL::text, p_payment_method text DEFAULT NULL::text, p_payment_ref text DEFAULT NULL::text, p_slip_url text DEFAULT NULL::text, p_delivery_slot text DEFAULT NULL::text) RETURNS TABLE(id uuid, order_no integer)
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_id uuid;
  v_order_no int;
  v_code text := nullif(upper(trim(coalesce(p_voucher_code, ''))), '');
  v_voucher gift_vouchers%rowtype;
  v_item jsonb;
  v_prod_id uuid;
  v_pp numeric;
  v_is_slab boolean;
  v_flavors jsonb;
  v_flavor_price numeric;
  v_label text;
  v_pc int;
  v_addons_sum numeric;
  v_box int;
  v_calc_subtotal numeric := 0;
  v_calc_pieces int := 0;
  v_has_slab boolean := false;
  v_delivery_fee numeric := 0;
  v_base_fee numeric := 0;
  v_discount numeric := 0;
  v_calc_total numeric;
  v_payment_status text := case
    when p_payment_method = 'bank_transfer' then 'awaiting_verification'
    else 'unpaid'
  end;
begin
  if v_code is not null then
    select * into v_voucher from gift_vouchers where code = v_code for update;
    if not found or not v_voucher.is_active then
      raise exception 'VOUCHER_INVALID';
    end if;
    if v_voucher.used_at is not null then
      raise exception 'VOUCHER_USED';
    end if;
  end if;

  -- Pass 1: recompute subtotal + piece count from trusted catalogue rows.
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select products.price_per_piece, coalesce(products.is_slab_product, false), coalesce(products.flavors, '[]'::jsonb)
      into v_pp, v_is_slab, v_flavors
      from products
      where products.id = nullif(v_item->>'product_id', '')::uuid and products.is_visible = true;
    if not found then
      raise exception 'PRICE_MISMATCH';
    end if;

    select coalesce(sum(a.price), 0) into v_addons_sum
      from jsonb_array_elements(coalesce(v_item->'addons', '[]'::jsonb)) as ai
      join addons a on a.id = ai->>'id' and a.is_enabled = true;

    v_box := coalesce((v_item->>'box_qty')::int, 1);
    if v_box < 1 then
      raise exception 'PRICE_MISMATCH';
    end if;

    if v_is_slab then
      v_label := v_item->>'package_label';
      select (f->>'price')::numeric into v_flavor_price
        from jsonb_array_elements(v_flavors) as f
        where f->>'name' = v_label
        limit 1;
      if v_flavor_price is null then
        raise exception 'PRICE_MISMATCH';
      end if;
      v_calc_subtotal := v_calc_subtotal + (v_flavor_price + v_addons_sum) * v_box;
      v_has_slab := true;
    else
      select packages.piece_count into v_pc
        from packages
        where packages.id = v_item->>'package_id' and packages.is_active = true;
      if v_pc is null then
        raise exception 'PRICE_MISMATCH';
      end if;
      v_calc_subtotal := v_calc_subtotal + (v_pp * v_pc + v_addons_sum) * v_box;
      v_calc_pieces := v_calc_pieces + v_pc * v_box;
    end if;
  end loop;

  if v_calc_pieces <= 0 and not v_has_slab then
    raise exception 'PRICE_MISMATCH';
  end if;

  select coalesce(dt.fee, 0) into v_delivery_fee
    from delivery_tiers dt
    where v_calc_pieces >= dt.min_pieces
      and (dt.max_pieces is null or v_calc_pieces <= dt.max_pieces)
    order by dt.min_pieces desc
    limit 1;
  v_delivery_fee := coalesce(v_delivery_fee, 0);

  if v_has_slab then
    select coalesce(dt.fee, 0) into v_base_fee
      from delivery_tiers dt
      where 1 >= dt.min_pieces and (dt.max_pieces is null or 1 <= dt.max_pieces)
      order by dt.min_pieces desc
      limit 1;
    v_base_fee := coalesce(v_base_fee, 0);
    if v_base_fee > v_delivery_fee then
      v_delivery_fee := v_base_fee;
    end if;
  end if;

  if v_code is not null then
    if coalesce(v_voucher.discount_type, 'fixed') = 'percent' then
      v_discount := round((v_calc_subtotal + v_delivery_fee) * coalesce(v_voucher.amount, 0) / 100);
    else
      v_discount := coalesce(v_voucher.amount, 0);
    end if;
  end if;

  v_calc_total := greatest(0, v_calc_subtotal + v_delivery_fee - v_discount);

  if abs(coalesce(p_total, 0) - v_calc_total) > 0.01 then
    raise exception 'PRICE_MISMATCH';
  end if;

  insert into orders (
    customer_name, phone, email, alt_phone, address, delivery_date, delivery_slot, note,
    subtotal, delivery_fee, total, total_pieces, status, source, inquiry_id,
    voucher_code, voucher_discount, is_gift, recipient_name, recipient_phone,
    payment_method, payment_status, payment_ref, slip_url
  )
  values (
    p_customer_name, p_phone, nullif(p_email, ''), nullif(p_alt_phone, ''),
    p_address, p_delivery_date, nullif(p_delivery_slot, ''), p_note,
    v_calc_subtotal, v_delivery_fee, v_calc_total, v_calc_pieces, 'pending', 'web', null,
    v_code, v_discount,
    coalesce(p_is_gift, false), nullif(p_recipient_name, ''), nullif(p_recipient_phone, ''),
    p_payment_method, v_payment_status, nullif(p_payment_ref, ''), nullif(p_slip_url, '')
  )
  returning orders.id, orders.order_no into v_id, v_order_no;

  if v_code is not null then
    update gift_vouchers
      set used_at = now(), used_by_order_id = v_id
      where code = v_code;
  end if;

  -- Pass 2: insert order_items with server-recomputed money. `products.*` is
  -- qualified so bare `id` never collides with the RETURNS TABLE `id` column.
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select products.id, products.price_per_piece, coalesce(products.is_slab_product, false), coalesce(products.flavors, '[]'::jsonb)
      into v_prod_id, v_pp, v_is_slab, v_flavors
      from products
      where products.id = nullif(v_item->>'product_id', '')::uuid and products.is_visible = true;

    select coalesce(sum(a.price), 0) into v_addons_sum
      from jsonb_array_elements(coalesce(v_item->'addons', '[]'::jsonb)) as ai
      join addons a on a.id = ai->>'id' and a.is_enabled = true;

    v_box := greatest(1, coalesce((v_item->>'box_qty')::int, 1));

    if v_is_slab then
      v_label := v_item->>'package_label';
      select (f->>'price')::numeric into v_flavor_price
        from jsonb_array_elements(v_flavors) as f
        where f->>'name' = v_label
        limit 1;
      insert into order_items (
        order_id, product_id, product_name, package_id, package_label,
        piece_count, box_qty, unit_price, addons, line_total
      )
      values (
        v_id, v_prod_id, v_item->>'product_name', null, v_label,
        0, v_box, v_flavor_price, coalesce(v_item->'addons', '[]'::jsonb),
        (v_flavor_price + v_addons_sum) * v_box
      );
    else
      select packages.piece_count into v_pc
        from packages
        where packages.id = v_item->>'package_id' and packages.is_active = true;
      insert into order_items (
        order_id, product_id, product_name, package_id, package_label,
        piece_count, box_qty, unit_price, addons, line_total
      )
      values (
        v_id, v_prod_id, v_item->>'product_name', v_item->>'package_id', v_item->>'package_label',
        v_pc, v_box, v_pp, coalesce(v_item->'addons', '[]'::jsonb),
        (v_pp * v_pc + v_addons_sum) * v_box
      );
    end if;
  end loop;

  return query select v_id, v_order_no;
end;
$$;


--
-- Name: get_catalog(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.get_catalog() RETURNS jsonb
    LANGUAGE sql STABLE SECURITY DEFINER
    AS $$
  select jsonb_build_object(
    'products', coalesce(
      (select jsonb_agg(to_jsonb(p) order by p.sort_order)
         from products p where p.is_visible), '[]'::jsonb),
    'packages', coalesce(
      (select jsonb_agg(to_jsonb(pk) order by pk.sort_order)
         from packages pk where pk.is_active), '[]'::jsonb),
    'addons', coalesce(
      (select jsonb_agg(to_jsonb(a)) from addons a), '[]'::jsonb),
    'categories', coalesce(
      (select jsonb_agg(to_jsonb(c) order by c.sort_order)
         from categories c where c.is_visible), '[]'::jsonb),
    'delivery_tiers', coalesce(
      (select jsonb_agg(to_jsonb(t) order by t.sort_order)
         from delivery_tiers t), '[]'::jsonb),
    'reviews', coalesce(
      (select jsonb_agg(to_jsonb(r)) from reviews r where r.is_featured), '[]'::jsonb),
    'site_settings', coalesce(
      (select jsonb_agg(to_jsonb(s)) from site_settings s), '[]'::jsonb),
    'product_package_stock', coalesce(
      (select jsonb_agg(to_jsonb(ps)) from product_package_stock ps), '[]'::jsonb),
    'product_package_availability', coalesce(
      (select jsonb_agg(to_jsonb(pa)) from product_package_availability pa), '[]'::jsonb)
  );
$$;


--
-- Name: is_admin(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.is_admin() RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    AS $$
  select coalesce(
    (select role from profiles where id = auth.uid()) = 'admin',
    auth.uid() is not null
  );
$$;


--
-- Name: lookup_order(integer, text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.lookup_order(p_order_no integer, p_phone text) RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_order orders%rowtype;
  v_items jsonb;
begin
  select * into v_order
  from orders
  where order_no = p_order_no and phone = p_phone;
  if not found then
    return null;
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'product_name', oi.product_name,
        'package_label', oi.package_label,
        'piece_count', oi.piece_count,
        'box_qty', oi.box_qty
      )
      order by oi.id
    ),
    '[]'::jsonb
  )
  into v_items
  from order_items oi
  where oi.order_id = v_order.id;

  return jsonb_build_object(
    'order_no', v_order.order_no,
    'status', v_order.status,
    'payment_status', v_order.payment_status,
    'customer_name', v_order.customer_name,
    'phone', v_order.phone,
    'address', v_order.address,
    'delivery_date', v_order.delivery_date,
    'delivery_slot', v_order.delivery_slot,
    'is_gift', v_order.is_gift,
    'recipient_name', v_order.recipient_name,
    'recipient_phone', v_order.recipient_phone,
    'items', v_items
  );
end;
$$;


--
-- Name: mark_order_paid(uuid, text, numeric); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.mark_order_paid(p_order_id uuid, p_payment_ref text, p_amount numeric) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v_total numeric;
begin
  select total into v_total from orders where id = p_order_id;
  if not found then
    raise exception 'ORDER_NOT_FOUND';
  end if;
  if abs(v_total - p_amount) > 0.01 then
    raise exception 'AMOUNT_MISMATCH';
  end if;
  update orders
    set payment_status = 'paid',
        payment_ref = coalesce(p_payment_ref, payment_ref),
        updated_at = now()
    where id = p_order_id;
end;
$$;


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin new.updated_at = now(); return new; end;
$$;


--
-- Name: validate_gift_voucher(text); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.validate_gift_voucher(p_code text) RETURNS TABLE(status text, amount numeric, discount_type text)
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
declare
  v gift_vouchers%rowtype;
begin
  select * into v from gift_vouchers where code = upper(trim(p_code));

  if not found or not v.is_active then
    return query select 'invalid'::text, null::numeric, null::text;
    return;
  end if;

  if v.used_at is not null then
    return query select 'used'::text, null::numeric, null::text;
    return;
  end if;

  return query select 'ok'::text, v.amount, v.discount_type;
end;
$$;




--
-- Name: addons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.addons (
    id text NOT NULL,
    label text NOT NULL,
    price numeric(10,2) DEFAULT 0 NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    is_visible boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


--
-- Name: delivery_tiers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.delivery_tiers (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    min_pieces integer NOT NULL,
    max_pieces integer,
    fee numeric(10,2) NOT NULL,
    warn_admin boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


--
-- Name: gift_vouchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gift_vouchers (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    code text NOT NULL,
    amount numeric(10,2) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    used_at timestamp with time zone,
    used_by_order_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    discount_type text DEFAULT 'fixed'::text NOT NULL,
    CONSTRAINT gift_vouchers_amount_check CHECK ((amount > (0)::numeric)),
    CONSTRAINT gift_vouchers_discount_type_check CHECK ((discount_type = ANY (ARRAY['fixed'::text, 'percent'::text])))
);


--
-- Name: COLUMN gift_vouchers.discount_type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.gift_vouchers.discount_type IS 'fixed = amount is a flat LKR discount; percent = amount is a percentage of (subtotal + delivery).';


--
-- Name: inquiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inquiries (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    category public.inquiry_category NOT NULL,
    status public.inquiry_status DEFAULT 'new'::public.inquiry_status NOT NULL,
    name text NOT NULL,
    phone text NOT NULL,
    email text,
    event_date date,
    guest_count integer,
    message text,
    converted_order_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ops_ad_spend; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_ad_spend (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    month date NOT NULL,
    channel text DEFAULT 'facebook'::text NOT NULL,
    amount_lkr numeric(12,2) DEFAULT 0 NOT NULL,
    amount_usd numeric(12,2),
    usd_rate numeric(10,4),
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ops_ad_spend_channel_check CHECK ((channel = ANY (ARRAY['facebook'::text, 'tiktok'::text, 'other'::text])))
);


--
-- Name: ops_b2b_pipeline; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_b2b_pipeline (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    tier text DEFAULT 'prospect'::text NOT NULL,
    industry text,
    customer text NOT NULL,
    solution text,
    value_000 numeric(12,2),
    contact text,
    status text DEFAULT 'prospect'::text NOT NULL,
    next_step text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ops_b2b_pipeline_status_check CHECK ((status = ANY (ARRAY['prospect'::text, 'new_sale'::text, 'retainer'::text, 'won'::text, 'lost'::text]))),
    CONSTRAINT ops_b2b_pipeline_tier_check CHECK ((tier = ANY (ARRAY['high'::text, 'medium'::text, 'prospect'::text, 'corporate'::text])))
);


--
-- Name: ops_investments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_investments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    investor text NOT NULL,
    item text,
    amount numeric(12,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ops_monthly_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_monthly_targets (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    month date NOT NULL,
    target_pcs integer DEFAULT 0 NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ops_operating_expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_operating_expenses (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    month date NOT NULL,
    category text DEFAULT 'other'::text NOT NULL,
    description text,
    amount_lkr numeric(12,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ops_operating_expenses_category_check CHECK ((category = ANY (ARRAY['salary'::text, 'box'::text, 'rent'::text, 'other'::text])))
);


--
-- Name: ops_purchases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_purchases (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    purchase_date date NOT NULL,
    item text NOT NULL,
    qty text,
    amount_lkr numeric(12,2) DEFAULT 0 NOT NULL,
    category text DEFAULT 'ingredient'::text NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ops_purchases_category_check CHECK ((category = ANY (ARRAY['ingredient'::text, 'packaging'::text, 'equipment'::text, 'other'::text])))
);


--
-- Name: ops_recipe_ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_recipe_ingredients (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    recipe_id uuid NOT NULL,
    name text NOT NULL,
    cost numeric(10,2) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


--
-- Name: ops_recipes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_recipes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    flavor text NOT NULL,
    per_piece_cost numeric(10,2) DEFAULT 0 NOT NULL,
    selling_price numeric(10,2) DEFAULT 0 NOT NULL,
    batch_pcs integer DEFAULT 20 NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: ops_sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_sales (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    channel text DEFAULT 'b2b'::text NOT NULL,
    sale_date date NOT NULL,
    flavor text,
    customer text,
    ref text,
    qty integer DEFAULT 0 NOT NULL,
    unit_price numeric(10,2) DEFAULT 0 NOT NULL,
    amount numeric(12,2) GENERATED ALWAYS AS (((qty)::numeric * unit_price)) STORED,
    discount numeric(10,2) DEFAULT 0 NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ops_sales_channel_check CHECK ((channel = ANY (ARRAY['b2b'::text, 'b2c'::text])))
);


--
-- Name: ops_shares; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ops_shares (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    holder text NOT NULL,
    share_pct numeric(6,4) DEFAULT 0 NOT NULL,
    earned numeric(12,2) DEFAULT 0 NOT NULL,
    paid numeric(12,2) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    order_id uuid NOT NULL,
    product_id uuid,
    product_name text NOT NULL,
    package_id text,
    package_label text NOT NULL,
    piece_count integer NOT NULL,
    box_qty integer DEFAULT 1 NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    unit_cost numeric(10,2),
    addons jsonb DEFAULT '[]'::jsonb NOT NULL,
    line_total numeric(10,2) NOT NULL,
    CONSTRAINT order_items_box_qty_check CHECK ((box_qty >= 1))
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    order_no integer NOT NULL,
    status public.order_status DEFAULT 'pending'::public.order_status NOT NULL,
    customer_name text NOT NULL,
    phone text NOT NULL,
    address text,
    delivery_date date,
    note text,
    subtotal numeric(10,2) NOT NULL,
    delivery_fee numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    total_pieces integer NOT NULL,
    source text DEFAULT 'web'::text NOT NULL,
    inquiry_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    email text,
    alt_phone text,
    voucher_code text,
    voucher_discount numeric(10,2) DEFAULT 0 NOT NULL,
    is_gift boolean DEFAULT false NOT NULL,
    recipient_name text,
    recipient_phone text,
    payment_method text,
    payment_status text DEFAULT 'unpaid'::text NOT NULL,
    payment_ref text,
    slip_url text,
    delivery_slot text,
    CONSTRAINT orders_delivery_slot_check CHECK (((delivery_slot IS NULL) OR (delivery_slot = ANY (ARRAY['10-11'::text, '16-18'::text])))),
    CONSTRAINT orders_payment_method_check CHECK ((payment_method = ANY (ARRAY['bank_transfer'::text, 'card'::text]))),
    CONSTRAINT orders_payment_status_check CHECK ((payment_status = ANY (ARRAY['unpaid'::text, 'awaiting_verification'::text, 'paid'::text, 'failed'::text])))
);


--
-- Name: COLUMN orders.email; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.orders.email IS 'Customer email captured at checkout (required at the app layer; nullable here for legacy/inquiry-converted rows).';


--
-- Name: COLUMN orders.alt_phone; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.orders.alt_phone IS 'Optional secondary contact number captured at checkout.';


--
-- Name: orders_order_no_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.orders_order_no_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: orders_order_no_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.orders_order_no_seq OWNED BY public.orders.order_no;


--
-- Name: packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.packages (
    id text NOT NULL,
    label text NOT NULL,
    piece_count integer NOT NULL,
    is_slab boolean DEFAULT false NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    letter_max_chars integer DEFAULT 0 NOT NULL,
    CONSTRAINT packages_piece_count_check CHECK ((piece_count > 0))
);


--
-- Name: COLUMN packages.letter_max_chars; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.packages.letter_max_chars IS 'Max characters per topper line (3 lines, spec unchanged) for this package. 0 = no topper offered.';


--
-- Name: product_package_availability; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_package_availability (
    product_id uuid NOT NULL,
    package_id text NOT NULL,
    is_available boolean DEFAULT true NOT NULL
);


--
-- Name: TABLE product_package_availability; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_package_availability IS 'Per product×package availability overrides. No row = available. A row exists only when admin has hidden that package for the product (is_available=false).';


--
-- Name: product_package_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_package_stock (
    product_id uuid NOT NULL,
    package_id text NOT NULL,
    in_stock boolean DEFAULT false NOT NULL
);


--
-- Name: TABLE product_package_stock; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.product_package_stock IS 'Per product×package sold-out overrides. No row = in stock. A row exists only when admin has explicitly marked that combo (almost always to mark it OUT of stock — in_stock=false); the table is not meant to hold one row per combo.';


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    category_id uuid,
    name text NOT NULL,
    slug text NOT NULL,
    description text,
    price_per_piece numeric(10,2) NOT NULL,
    image_url text,
    is_visible boolean DEFAULT true NOT NULL,
    in_stock boolean DEFAULT true NOT NULL,
    stock_qty integer,
    is_slab_available boolean DEFAULT false NOT NULL,
    allows_letter_topper boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    media jsonb DEFAULT '[]'::jsonb NOT NULL,
    is_slab_15_available boolean DEFAULT false NOT NULL,
    is_hot_pick boolean DEFAULT false NOT NULL,
    is_corporate boolean DEFAULT false NOT NULL,
    is_slab_product boolean DEFAULT false NOT NULL,
    flavors jsonb DEFAULT '[]'::jsonb NOT NULL,
    slab_letter_max_chars integer DEFAULT 7 NOT NULL,
    CONSTRAINT products_price_per_piece_check CHECK ((price_per_piece >= (0)::numeric)),
    CONSTRAINT products_slab_letter_max_chars_check CHECK (((slab_letter_max_chars >= 0) AND (slab_letter_max_chars <= 20)))
);


--
-- Name: COLUMN products.is_slab_available; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.is_slab_available IS 'Can be ordered as the 12pc Brownie Slab (slab-12). Independent of is_slab_15_available.';


--
-- Name: COLUMN products.media; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.media IS 'Ordered gallery: [{"url": "...", "type": "image"|"video"}, ...]. media[0] is the cover, mirrored into image_url.';


--
-- Name: COLUMN products.is_slab_15_available; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.is_slab_15_available IS 'Can be ordered as the 15pc Brownie Slab (slab-15). Independent of is_slab_available.';


--
-- Name: COLUMN products.is_hot_pick; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.is_hot_pick IS 'Featured on the homepage Hot Picks section (below the hero). Admin-toggled.';


--
-- Name: COLUMN products.is_slab_product; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.is_slab_product IS 'Standalone Brownie Slab product — priced per product via `flavors`, flavour selector on the PDP.';


--
-- Name: COLUMN products.flavors; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.flavors IS 'Slab flavours: JSONB array of { "name": text, "price": number }. Empty for non-slab products.';


--
-- Name: COLUMN products.slab_letter_max_chars; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.products.slab_letter_max_chars IS 'Letter-topper characters allowed PER LINE on a standalone slab product (is_slab_product = true). The number of lines is fixed at 3 (TOPPER_LINES). Ignored for package-based products, which read packages.letter_max_chars. 0 disables the topper for this slab.';


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    role text DEFAULT 'admin'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'kitchen'::text, 'finance'::text])))
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    author text NOT NULL,
    rating integer NOT NULL,
    body text NOT NULL,
    source text DEFAULT 'google'::text NOT NULL,
    is_featured boolean DEFAULT false NOT NULL,
    is_hidden boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: site_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_settings (
    key text NOT NULL,
    value jsonb NOT NULL
);


--
-- Name: orders order_no; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders ALTER COLUMN order_no SET DEFAULT nextval('public.orders_order_no_seq'::regclass);


--
-- Name: addons addons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.addons
    ADD CONSTRAINT addons_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: categories categories_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_slug_key UNIQUE (slug);


--
-- Name: delivery_tiers delivery_tiers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.delivery_tiers
    ADD CONSTRAINT delivery_tiers_pkey PRIMARY KEY (id);


--
-- Name: gift_vouchers gift_vouchers_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gift_vouchers
    ADD CONSTRAINT gift_vouchers_code_key UNIQUE (code);


--
-- Name: gift_vouchers gift_vouchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gift_vouchers
    ADD CONSTRAINT gift_vouchers_pkey PRIMARY KEY (id);


--
-- Name: inquiries inquiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_pkey PRIMARY KEY (id);


--
-- Name: ops_ad_spend ops_ad_spend_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_ad_spend
    ADD CONSTRAINT ops_ad_spend_pkey PRIMARY KEY (id);


--
-- Name: ops_b2b_pipeline ops_b2b_pipeline_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_b2b_pipeline
    ADD CONSTRAINT ops_b2b_pipeline_pkey PRIMARY KEY (id);


--
-- Name: ops_investments ops_investments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_investments
    ADD CONSTRAINT ops_investments_pkey PRIMARY KEY (id);


--
-- Name: ops_monthly_targets ops_monthly_targets_month_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_monthly_targets
    ADD CONSTRAINT ops_monthly_targets_month_key UNIQUE (month);


--
-- Name: ops_monthly_targets ops_monthly_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_monthly_targets
    ADD CONSTRAINT ops_monthly_targets_pkey PRIMARY KEY (id);


--
-- Name: ops_operating_expenses ops_operating_expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_operating_expenses
    ADD CONSTRAINT ops_operating_expenses_pkey PRIMARY KEY (id);


--
-- Name: ops_purchases ops_purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_purchases
    ADD CONSTRAINT ops_purchases_pkey PRIMARY KEY (id);


--
-- Name: ops_recipe_ingredients ops_recipe_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_recipe_ingredients
    ADD CONSTRAINT ops_recipe_ingredients_pkey PRIMARY KEY (id);


--
-- Name: ops_recipes ops_recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_recipes
    ADD CONSTRAINT ops_recipes_pkey PRIMARY KEY (id);


--
-- Name: ops_sales ops_sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_sales
    ADD CONSTRAINT ops_sales_pkey PRIMARY KEY (id);


--
-- Name: ops_shares ops_shares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_shares
    ADD CONSTRAINT ops_shares_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_order_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_order_no_key UNIQUE (order_no);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: packages packages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.packages
    ADD CONSTRAINT packages_pkey PRIMARY KEY (id);


--
-- Name: product_package_availability product_package_availability_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_package_availability
    ADD CONSTRAINT product_package_availability_pkey PRIMARY KEY (product_id, package_id);


--
-- Name: product_package_stock product_package_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_package_stock
    ADD CONSTRAINT product_package_stock_pkey PRIMARY KEY (product_id, package_id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: products products_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_slug_key UNIQUE (slug);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: site_settings site_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_settings
    ADD CONSTRAINT site_settings_pkey PRIMARY KEY (key);


--
-- Name: ops_ad_spend_month_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ops_ad_spend_month_idx ON public.ops_ad_spend USING btree (month);


--
-- Name: ops_operating_expenses_month_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ops_operating_expenses_month_idx ON public.ops_operating_expenses USING btree (month);


--
-- Name: ops_purchases_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ops_purchases_date_idx ON public.ops_purchases USING btree (purchase_date);


--
-- Name: ops_recipe_ingredients_recipe_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ops_recipe_ingredients_recipe_idx ON public.ops_recipe_ingredients USING btree (recipe_id);


--
-- Name: ops_sales_channel_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ops_sales_channel_idx ON public.ops_sales USING btree (channel);


--
-- Name: ops_sales_date_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ops_sales_date_idx ON public.ops_sales USING btree (sale_date);


--
-- Name: orders_delivery_schedule_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX orders_delivery_schedule_idx ON public.orders USING btree (delivery_date, delivery_slot);


--
-- Name: ops_ad_spend ops_ad_spend_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_ad_spend_updated_at BEFORE UPDATE ON public.ops_ad_spend FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_b2b_pipeline ops_b2b_pipeline_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_b2b_pipeline_updated_at BEFORE UPDATE ON public.ops_b2b_pipeline FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_monthly_targets ops_monthly_targets_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_monthly_targets_updated_at BEFORE UPDATE ON public.ops_monthly_targets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_operating_expenses ops_operating_expenses_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_operating_expenses_updated_at BEFORE UPDATE ON public.ops_operating_expenses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_purchases ops_purchases_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_purchases_updated_at BEFORE UPDATE ON public.ops_purchases FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_recipes ops_recipes_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_recipes_updated_at BEFORE UPDATE ON public.ops_recipes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_sales ops_sales_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_sales_updated_at BEFORE UPDATE ON public.ops_sales FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: ops_shares ops_shares_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER ops_shares_updated_at BEFORE UPDATE ON public.ops_shares FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: orders orders_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: gift_vouchers gift_vouchers_used_by_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gift_vouchers
    ADD CONSTRAINT gift_vouchers_used_by_order_id_fkey FOREIGN KEY (used_by_order_id) REFERENCES public.orders(id) ON DELETE SET NULL;


--
-- Name: inquiries inquiries_converted_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inquiries
    ADD CONSTRAINT inquiries_converted_order_id_fkey FOREIGN KEY (converted_order_id) REFERENCES public.orders(id);


--
-- Name: ops_recipe_ingredients ops_recipe_ingredients_recipe_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ops_recipe_ingredients
    ADD CONSTRAINT ops_recipe_ingredients_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.ops_recipes(id) ON DELETE CASCADE;


--
-- Name: order_items order_items_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: order_items order_items_package_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id);


--
-- Name: order_items order_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;


--
-- Name: orders orders_inquiry_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_inquiry_id_fkey FOREIGN KEY (inquiry_id) REFERENCES public.inquiries(id) ON DELETE SET NULL;


--
-- Name: product_package_availability product_package_availability_package_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_package_availability
    ADD CONSTRAINT product_package_availability_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;


--
-- Name: product_package_availability product_package_availability_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_package_availability
    ADD CONSTRAINT product_package_availability_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: product_package_stock product_package_stock_package_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_package_stock
    ADD CONSTRAINT product_package_stock_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id) ON DELETE CASCADE;


--
-- Name: product_package_stock product_package_stock_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_package_stock
    ADD CONSTRAINT product_package_stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: products products_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE SET NULL;


--
-- Name: profiles profiles_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: addons; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;

--
-- Name: addons admin all addons; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all addons" ON public.addons USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: categories admin all categories; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all categories" ON public.categories USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: delivery_tiers admin all delivery tiers; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all delivery tiers" ON public.delivery_tiers USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: packages admin all packages; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all packages" ON public.packages USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: product_package_availability admin all product package availability; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all product package availability" ON public.product_package_availability USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));


--
-- Name: product_package_stock admin all product package stock; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all product package stock" ON public.product_package_stock USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: products admin all products; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all products" ON public.products USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: reviews admin all reviews; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all reviews" ON public.reviews USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: site_settings admin all settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin all settings" ON public.site_settings USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: inquiries admin manage inquiries; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin manage inquiries" ON public.inquiries USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: order_items admin manage order items; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin manage order items" ON public.order_items USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: orders admin manage orders; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "admin manage orders" ON public.orders USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: categories; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

--
-- Name: delivery_tiers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.delivery_tiers ENABLE ROW LEVEL SECURITY;

--
-- Name: gift_vouchers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.gift_vouchers ENABLE ROW LEVEL SECURITY;

--
-- Name: gift_vouchers gift_vouchers_admin_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY gift_vouchers_admin_all ON public.gift_vouchers USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: inquiries; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_ad_spend ops view ops_ad_spend; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_ad_spend" ON public.ops_ad_spend USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_b2b_pipeline ops view ops_b2b_pipeline; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_b2b_pipeline" ON public.ops_b2b_pipeline USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_investments ops view ops_investments; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_investments" ON public.ops_investments USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_monthly_targets ops view ops_monthly_targets; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_monthly_targets" ON public.ops_monthly_targets USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_operating_expenses ops view ops_operating_expenses; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_operating_expenses" ON public.ops_operating_expenses USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_purchases ops view ops_purchases; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_purchases" ON public.ops_purchases USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_recipe_ingredients ops view ops_recipe_ingredients; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_recipe_ingredients" ON public.ops_recipe_ingredients USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_recipes ops view ops_recipes; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_recipes" ON public.ops_recipes USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_sales ops view ops_sales; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_sales" ON public.ops_sales USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_shares ops view ops_shares; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "ops view ops_shares" ON public.ops_shares USING (public.can_view_ops()) WITH CHECK (public.can_view_ops());


--
-- Name: ops_ad_spend; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_ad_spend ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_b2b_pipeline; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_b2b_pipeline ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_investments; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_investments ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_monthly_targets; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_monthly_targets ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_operating_expenses; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_operating_expenses ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_purchases; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_purchases ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_recipe_ingredients; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_recipe_ingredients ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_recipes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_recipes ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_sales; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_sales ENABLE ROW LEVEL SECURITY;

--
-- Name: ops_shares; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ops_shares ENABLE ROW LEVEL SECURITY;

--
-- Name: order_items; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

--
-- Name: orders; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

--
-- Name: packages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;

--
-- Name: product_package_availability; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_package_availability ENABLE ROW LEVEL SECURITY;

--
-- Name: product_package_stock; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_package_stock ENABLE ROW LEVEL SECURITY;

--
-- Name: products; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles profiles_admin_all; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY profiles_admin_all ON public.profiles USING (public.is_admin()) WITH CHECK (public.is_admin());


--
-- Name: profiles profiles_select_own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY profiles_select_own ON public.profiles FOR SELECT USING ((auth.uid() = id));


--
-- Name: inquiries public create inquiry; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public create inquiry" ON public.inquiries FOR INSERT WITH CHECK (((status = 'new'::public.inquiry_status) AND (converted_order_id IS NULL)));


--
-- Name: packages public read active packages; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read active packages" ON public.packages FOR SELECT USING ((is_active = true));


--
-- Name: delivery_tiers public read delivery tiers; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read delivery tiers" ON public.delivery_tiers FOR SELECT USING (true);


--
-- Name: addons public read enabled addons; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read enabled addons" ON public.addons FOR SELECT USING ((is_enabled = true));


--
-- Name: reviews public read featured reviews; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read featured reviews" ON public.reviews FOR SELECT USING (((is_featured = true) AND (is_hidden = false)));


--
-- Name: product_package_availability public read product package availability; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read product package availability" ON public.product_package_availability FOR SELECT USING (true);


--
-- Name: product_package_stock public read product package stock; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read product package stock" ON public.product_package_stock FOR SELECT USING (true);


--
-- Name: site_settings public read public settings; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read public settings" ON public.site_settings FOR SELECT USING ((key = ANY (ARRAY['banner'::text, 'features'::text, 'business'::text])));


--
-- Name: categories public read visible categories; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read visible categories" ON public.categories FOR SELECT USING ((is_visible = true));


--
-- Name: products public read visible products; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "public read visible products" ON public.products FOR SELECT USING ((is_visible = true));


--
-- Name: reviews; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

--
-- Name: site_settings; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

--
-- Name: site_settings site_settings_public_read; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY site_settings_public_read ON public.site_settings FOR SELECT USING ((key = ANY (ARRAY['banner'::text, 'features'::text, 'business'::text, 'bank_transfer'::text])));


--
-- Name: order_items staff read order items; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "staff read order items" ON public.order_items FOR SELECT TO authenticated USING (true);


--
-- Name: orders staff read orders; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "staff read orders" ON public.orders FOR SELECT TO authenticated USING (true);


--
-- Name: FUNCTION advance_order_status(p_id uuid, p_to public.order_status); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.advance_order_status(p_id uuid, p_to public.order_status) FROM PUBLIC;
GRANT ALL ON FUNCTION public.advance_order_status(p_id uuid, p_to public.order_status) TO authenticated;


--
-- Name: FUNCTION can_view_ops(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.can_view_ops() FROM PUBLIC;
GRANT ALL ON FUNCTION public.can_view_ops() TO anon;
GRANT ALL ON FUNCTION public.can_view_ops() TO authenticated;


--
-- Name: FUNCTION create_order(p_customer_name text, p_phone text, p_email text, p_alt_phone text, p_address text, p_delivery_date date, p_note text, p_subtotal numeric, p_delivery_fee numeric, p_total numeric, p_total_pieces integer, p_items jsonb, p_voucher_code text, p_voucher_discount numeric, p_is_gift boolean, p_recipient_name text, p_recipient_phone text, p_payment_method text, p_payment_ref text, p_slip_url text, p_delivery_slot text); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.create_order(p_customer_name text, p_phone text, p_email text, p_alt_phone text, p_address text, p_delivery_date date, p_note text, p_subtotal numeric, p_delivery_fee numeric, p_total numeric, p_total_pieces integer, p_items jsonb, p_voucher_code text, p_voucher_discount numeric, p_is_gift boolean, p_recipient_name text, p_recipient_phone text, p_payment_method text, p_payment_ref text, p_slip_url text, p_delivery_slot text) TO anon;
GRANT ALL ON FUNCTION public.create_order(p_customer_name text, p_phone text, p_email text, p_alt_phone text, p_address text, p_delivery_date date, p_note text, p_subtotal numeric, p_delivery_fee numeric, p_total numeric, p_total_pieces integer, p_items jsonb, p_voucher_code text, p_voucher_discount numeric, p_is_gift boolean, p_recipient_name text, p_recipient_phone text, p_payment_method text, p_payment_ref text, p_slip_url text, p_delivery_slot text) TO authenticated;


--
-- Name: FUNCTION get_catalog(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.get_catalog() FROM PUBLIC;
GRANT ALL ON FUNCTION public.get_catalog() TO anon;
GRANT ALL ON FUNCTION public.get_catalog() TO authenticated;


--
-- Name: FUNCTION is_admin(); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
GRANT ALL ON FUNCTION public.is_admin() TO anon;
GRANT ALL ON FUNCTION public.is_admin() TO authenticated;


--
-- Name: FUNCTION lookup_order(p_order_no integer, p_phone text); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.lookup_order(p_order_no integer, p_phone text) TO anon;
GRANT ALL ON FUNCTION public.lookup_order(p_order_no integer, p_phone text) TO authenticated;


--
-- Name: FUNCTION mark_order_paid(p_order_id uuid, p_payment_ref text, p_amount numeric); Type: ACL; Schema: public; Owner: -
--

REVOKE ALL ON FUNCTION public.mark_order_paid(p_order_id uuid, p_payment_ref text, p_amount numeric) FROM PUBLIC;
GRANT ALL ON FUNCTION public.mark_order_paid(p_order_id uuid, p_payment_ref text, p_amount numeric) TO service_role;


--
-- Name: FUNCTION validate_gift_voucher(p_code text); Type: ACL; Schema: public; Owner: -
--

GRANT ALL ON FUNCTION public.validate_gift_voucher(p_code text) TO anon;
GRANT ALL ON FUNCTION public.validate_gift_voucher(p_code text) TO authenticated;


--
-- PostgreSQL database dump complete
--

\unrestrict yVAxHxeteQh6057YPAvnZ4WJUoMxENbsRroP9zCCtUT8sXiZ6mIxXXXNYnahFgU


-- ============================================================================
-- STORAGE — buckets and their policies
--
-- Lives in the `storage` schema, which a public-schema dump does not cover, so
-- these are carried over verbatim from migrations 026/027 and storage-setup.sql.
--
-- Reminder: this creates the buckets and their access rules, NOT their
-- contents. Product images and bank slips must be copied across separately or
-- images will 404 on the storefront.
-- ============================================================================

-- product-images (PUBLIC): admin-uploaded product gallery media.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images', 'product-images', true,
  52428800, -- 50 MB per file — comfortably covers a short product video
  array['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime']
)
on conflict (id) do update set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public read product-images" on storage.objects;
create policy "public read product-images"
  on storage.objects for select
  using (bucket_id = 'product-images');

drop policy if exists "admin write product-images" on storage.objects;
create policy "admin write product-images"
  on storage.objects for all
  using (bucket_id = 'product-images' and auth.role() = 'authenticated')
  with check (bucket_id = 'product-images' and auth.role() = 'authenticated');

-- bank-slips (PRIVATE): customer payment slips. Anyone may upload at checkout;
-- only signed-in staff may read, and only via short-lived signed URLs.
insert into storage.buckets (id, name, public)
values ('bank-slips', 'bank-slips', false)
on conflict (id) do nothing;

drop policy if exists "bank_slips_anon_insert" on storage.objects;
create policy "bank_slips_anon_insert" on storage.objects
  for insert to anon, authenticated
  with check (bucket_id = 'bank-slips');

drop policy if exists "bank_slips_admin_read" on storage.objects;
create policy "bank_slips_admin_read" on storage.objects
  for select to authenticated
  using (bucket_id = 'bank-slips');


-- ============================================================================
-- NEXT STEPS
--   1. Create your admin / kitchen / finance users (Authentication → Users),
--      or let them arrive with your auth-schema data import.
--   2. Kitchen and finance accounts need a profiles row naming their role:
--        insert into profiles (id, role)
--        select id, 'kitchen' from auth.users where email = 'kitchen@example.com'
--        on conflict (id) do update set role = 'kitchen';
--      Admins need no row (no row = admin), so this is only for the other two.
--   3. Point both apps at the new project: VITE_SUPABASE_URL and
--      VITE_SUPABASE_ANON_KEY (plus SUPABASE_SERVICE_KEY on the storefront),
--      then REDEPLOY both — Vite bakes these in at build time, so saving them
--      in Vercel changes nothing until a rebuild.
-- ============================================================================
