#!/usr/bin/env bash
set -euo pipefail

# Fixes the whole page scrolling horizontally on mobile (Build-your-slab /
# gift-ready grid was letting its horizontal-scroll strip stretch the entire
# row past the viewport). One-line-per-card fix.
#
# Clones into an isolated, branch-named directory ("gowebsite-claude-home-horizontal-overflow-fix") so it can't
# collide with your Codespace's own checkout or leftovers from earlier runs.

REPO_URL="https://github.com/yoosuf0806/go-website.git"
BRANCH="claude/home-horizontal-overflow-fix"
DIR="gowebsite-claude-home-horizontal-overflow-fix"

if [ -d "$DIR" ]; then
  echo "$DIR already exists here (probably from a previous run of this exact script) — remove it first:" >&2
  echo "  rm -rf $DIR" >&2
  exit 1
fi

echo "Cloning fresh main into $DIR..."
git clone "$REPO_URL" "$DIR"
cd "$DIR"
git checkout -b "$BRANCH"

echo "Applying patch..."
base64 -d <<'PATCH_B64' | git am
RnJvbSA5ZGI4YWViNzMxNjc3NzJkMGY2MDFhMmIxZGQzMDdiNWZjMjU5MDlhIE1vbiBTZXAgMTcgMDA6MDA6MDAgMjAwMQpGcm9tOiBDbGF1ZGUgPGNsYXVkZUBhbnRocm9waWMuY29tPgpEYXRlOiBTYXQsIDEgQXVnIDIwMjYgMTY6MjY6MDIgKzAwMDAKU3ViamVjdDogW1BBVENIXSBmaXgoaG9tZSk6IHN0b3AgdGhlIHdob2xlIHBhZ2Ugc2Nyb2xsaW5nIGhvcml6b250YWxseSBvbgogbW9iaWxlCk1JTUUtVmVyc2lvbjogMS4wCkNvbnRlbnQtVHlwZTogdGV4dC9wbGFpbjsgY2hhcnNldD1VVEYtOApDb250ZW50LVRyYW5zZmVyLUVuY29kaW5nOiA4Yml0CgpUaGUgQnVpbGQteW91ci1zbGFiIC8gSXQtYXJyaXZlcy1naWZ0LXJlYWR5IHBhaXIgc2l0cyBpbnNpZGUgYSBDU1MgR3JpZAooZ3JpZCBvbiBtb2JpbGUgdG9vLCBub3QganVzdCBtZDpncmlkLWNvbHMtMikuIEdyaWQgaXRlbXMgZGVmYXVsdCB0bwptaW4td2lkdGg6IGF1dG8sIHNvIHRoZSBnaWZ0LXJlYWR5IGNhcmQncyB1bmNvbnN0cmFpbmVkIGhvcml6b250YWwKc2Nyb2xsIHN0cmlwICg0IGZpeGVkLXdpZHRoIGltYWdlcywgfjgzMHB4IHVud3JhcHBlZCkgcmVwb3J0ZWQgaXRzIGZ1bGwKY29udGVudCB3aWR0aCBiYWNrIHRvIHRoZSBncmlkLCBzdHJldGNoaW5nIHRoZSBzaW5nbGUtY29sdW1uIHJvdyBwYXN0CnRoZSAzOTBweCB2aWV3cG9ydCBhbmQgbWFraW5nIHRoZSBlbnRpcmUgcGFnZSBzY3JvbGwgc2lkZXdheXMg4oCUIG5vdApqdXN0IHRoYXQgb25lIHN0cmlwLgoKQWRkcyBtaW4tdy0wIHRvIGJvdGggZ3JpZC1pdGVtIGNhcmRzIHNvIHRoZSBncmlkIGNhbiBzaXplIHRoZW0gdG8gdGhlCnZpZXdwb3J0IGFuZCBsZXQgdGhlIGlubmVyIG92ZXJmbG93LXgtYXV0byBzdHJpcCBkbyB0aGUgc2Nyb2xsaW5nCml0c2VsZiwgYXMgaW50ZW5kZWQuCgpBdWRpdGVkIGV2ZXJ5IG90aGVyIG92ZXJmbG93LXgtYXV0byBzdHJpcCBzaXRld2lkZSAoU2hvcCdzIGNhdGVnb3J5CmNoaXBzLCBIb21lJ3MgSG90IFBpY2tzIGNhcm91c2VsLCBQcm9kdWN0IERldGFpbCdzIGNyb3NzLXNlbGwgc3RyaXAsIHRoZQpDb3Jwb3JhdGUvV2VkZGluZyBvY2Nhc2lvbnMgc3RyaXAsIGFkbWluJ3MgZGF0YSB0YWJsZXMpIOKAlCBhbGwgb2YgdGhlbQpzaXQgdW5kZXIgYSBwbGFpbiBibG9jayBjb250YWluZXIsIG5vdCBhIGdyaWQsIHNvIHRoZXkgY2xpcCBjb3JyZWN0bHkKYWxyZWFkeS4gVGhpcyB3YXMgdGhlIG9ubHkgc2l0ZSB3aXRoIHRoZSBidWcuCi0tLQogc3JjL3BhZ2VzL0hvbWUudHN4IHwgNCArKy0tCiAxIGZpbGUgY2hhbmdlZCwgMiBpbnNlcnRpb25zKCspLCAyIGRlbGV0aW9ucygtKQoKZGlmZiAtLWdpdCBhL3NyYy9wYWdlcy9Ib21lLnRzeCBiL3NyYy9wYWdlcy9Ib21lLnRzeAppbmRleCA1M2E2NjY5Li4wMTU5MjYxIDEwMDY0NAotLS0gYS9zcmMvcGFnZXMvSG9tZS50c3gKKysrIGIvc3JjL3BhZ2VzL0hvbWUudHN4CkBAIC0xMTksNyArMTE5LDcgQEAgZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gSG9tZSgpIHsKICAgICAgIDxzZWN0aW9uIGNsYXNzTmFtZT0icHQtNiBtZDpweS0xNCI+CiAgICAgICAgIDxkaXYgY2xhc3NOYW1lPSJteC1hdXRvIGdyaWQgbWF4LXctNnhsIGdhcC02IHB4LVsyMnB4XSBtZDpncmlkLWNvbHMtMiBtZDpnYXAtOCBtZDpweC04Ij4KICAgICAgICAgICB7LyogQnVpbGQgeW91ciBvd24gc2xhYiAqL30KLSAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBmbGV4LWNvbCByb3VuZGVkLVsyMHB4XSBib3JkZXIgYm9yZGVyLWJsdXNoLTIwMCBiZy13aGl0ZSBwLTUgbWQ6cC03Ij4KKyAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBtaW4tdy0wIGZsZXgtY29sIHJvdW5kZWQtWzIwcHhdIGJvcmRlciBib3JkZXItYmx1c2gtMjAwIGJnLXdoaXRlIHAtNSBtZDpwLTciPgogICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LVsxMXB4XSBmb250LW1lZGl1bSB1cHBlcmNhc2UgdHJhY2tpbmctWzAuMThlbV0gdGV4dC1iZXJyeSI+e2hvbWVTbGFiLmV5ZWJyb3d9PC9zcGFuPgogICAgICAgICAgICAgPGgyIGNsYXNzTmFtZT0ibXQtMiBmb250LWRpc3BsYXkgdGV4dC1bMjdweF0gbGVhZGluZy1bMS4xNF0gdGV4dC1uYXZ5IG1kOnRleHQtWzMycHhdIj57aG9tZVNsYWIudGl0bGV9PC9oMj4KICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMiB0ZXh0LVsxNXB4XSBsZWFkaW5nLXJlbGF4ZWQgdGV4dC1bIzVjNDQ1MF0iPntob21lU2xhYi5ib2R5fTwvcD4KQEAgLTEzNSw3ICsxMzUsNyBAQCBleHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBIb21lKCkgewogICAgICAgICAgIDwvZGl2PgogCiAgICAgICAgICAgey8qIEl0IGFycml2ZXMgZ2lmdC1yZWFkeSAqL30KLSAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBmbGV4LWNvbCByb3VuZGVkLVsyMHB4XSBib3JkZXIgYm9yZGVyLWJsdXNoLTIwMCBiZy13aGl0ZSBwLTUgbWQ6cC03Ij4KKyAgICAgICAgICA8ZGl2IGNsYXNzTmFtZT0iZmxleCBtaW4tdy0wIGZsZXgtY29sIHJvdW5kZWQtWzIwcHhdIGJvcmRlciBib3JkZXItYmx1c2gtMjAwIGJnLXdoaXRlIHAtNSBtZDpwLTciPgogICAgICAgICAgICAgPHNwYW4gY2xhc3NOYW1lPSJ0ZXh0LVsxMXB4XSBmb250LW1lZGl1bSB1cHBlcmNhc2UgdHJhY2tpbmctWzAuMThlbV0gdGV4dC1iZXJyeSI+R2lmdC1yZWFkeTwvc3Bhbj4KICAgICAgICAgICAgIDxoMiBjbGFzc05hbWU9Im10LTIgZm9udC1kaXNwbGF5IHRleHQtWzI3cHhdIGxlYWRpbmctWzEuMTRdIHRleHQtbmF2eSBtZDp0ZXh0LVszMnB4XSI+SXQgYXJyaXZlcyBnaWZ0LXJlYWR5PC9oMj4KICAgICAgICAgICAgIDxwIGNsYXNzTmFtZT0ibXQtMiB0ZXh0LVsxNXB4XSBsZWFkaW5nLXJlbGF4ZWQgdGV4dC1bIzVjNDQ1MF0iPgotLSAKMi40My4wCgo=
PATCH_B64

echo
echo "Patch applied cleanly on branch $BRANCH in ./$DIR"
echo "Next steps:"
echo "  cd $DIR"
echo "  git push -u origin $BRANCH"
echo "  Open a PR: https://github.com/yoosuf0806/go-website/compare/main...$BRANCH"
